### ISSUE TITLE
Unknown references on project re-open

### ISSUE THREAD

**Issue by quimnuss** [kamrann/KantanCharts#5]
Restarting the editor fails to recognize everything related to Kantan in Blueprints. However, the functions do exist because I can readd them. 

The error message says "Failed to load /Script/KantanChargsUMG.SimpleTimeSeriesPlot Referenced by K2Node_CallFunction_0"

The function calls in the blueprint get renamed to "BP Add Series With Id"

Let me know if I can gather any further information, great plugin for plotting!

UE4 4.23.1

**Comment by quimnuss** [comment]
I've noticed this error only happens when anything that contains kantan is used on UMG

**Comment by quimnuss** [comment]
Correction, it only happens when anything that contains a kantan function/object is used on the Graph part of a widget. It works otherwise.

**Comment by kamrann** [comment]
I assume the 'KantanChar-->g<--sUMG' in the message is just a typo and not the actual output?

Generally when you get those errors on load but can re-add nodes, it implies a problem with loading order - something is causing your widget blueprint to be loaded too early in the startup process, before the plugin modules have been loaded. Are you perhaps referencing the widget blueprint directly from C++ code?

**Comment by quimnuss** [comment]
I believe you are correct. I was including the header file on the C++ HUD class and now that I've removed that part I couldn't reproduce the issue. 

Case closed.
