### ISSUE TITLE
Cooking in Linux fails: Missing precompiled manifest for 'KantanChartsDatasource'

### ISSUE THREAD

**Issue by quimnuss** [kamrann/KantanCharts#6]
I'm cross-compiling a project with KantanCharts.

Cooking for Windows works fine, but for Linux the log says:

```
********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Linux): Running: D:\Epic Games\UE_4.25\Engine\Binaries\DotNET\UnrealBuildTool.exe testLinux Development -Project=D:\ue4projects\test\test.uproject  D:\ue4projects\test\test.uproject -NoUBTMakefiles  -remoteini="D:\ue4projects\test" -skipdeploy -Manifest=D:\ue4projects\test\Intermedi
ate\Build\Manifest.xml -NoHotReload -log="C:\Users\me\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+yoqs+Epic+Games+UE_4.25\UBT-test-Linux-Development.txt"
UATHelper: Packaging (Linux):   Using 'git status' to determine working set for adaptive non-unity build (D:\ue4projects\test).
UATHelper: Packaging (Linux):   ERROR: Missing precompiled manifest for 'KantanChartsDatasource'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in KantanChartsDatasource.build.cs to override.
PackagingResults: Error: Missing precompiled manifest for 'KantanChartsDatasource'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in KantanChartsDatasource.build.cs to override.
```

Any ideas how to add it?

Using UE4.25

**Comment by kamrann** [comment]
Not sure I can be much help here, I haven't done any testing on Linux. It is marked for Linux compatibility on the marketplace and in the uplugin file. I notice if I install via launcher on Windows it doesn't have any Linux data in the intermediate folder, though perhaps that's just the launcher filtering it out.

Anyway I guess you're building the plugin from source. What is your process - is the plugin installed in the project, or to the engine? And did you try making the change it mentions in the pasted output?

**Comment by quimnuss** [comment]
I was using the marketplace Kantan, so I tried with the source directly as per your suggestion on a new dummy project. 

I've placed the code inside Plugins, deleted the Intermediate directory, restart the project and rebuild.

It does work without errors (had to delete the Intermediate and rebuild the UE4 solution), but I guess it hasn't taken into account the plugin because it's not accessible from the ue4 editor as if it weren't there.

I'll try to find out how to build a plugin from source so that it's recognized by the Editor and get back to you.

**Comment by kamrann** [comment]
Did you put it in Engine/Plugins, or YourProject/Plugins?
Either way, you should check that your have it added and enabled in the "Plugins": [] list within your .uproject file.

**Comment by quimnuss** [comment]
Ha! that was the trick. It built successfully now.

I've placed the github Plugin under MyProject/Plugins and then you can activate it via Edit -> Plugins. I had missed it because that menu has 2 sections, `Built-in` and `Project`, which is at the very bottom. Once it was enabled the build succeeded.

Now I just have to try it with the real thing.

I close the issue. Thanks for the prompt answer!
